# Site settings
title: A Society of Things
header-img: img/home-bg.jpg
email: phil@windley.org
description: "Social Things Working for You"
baseurl: ""
url: "http://societyofthings.org"
twitter_username: windley
github_username:  windley
facebook_username:  windley

# Build settings
markdown: kramdown
highlighter: pygments
permalink: none
# paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
