# Site settings
title: Society Of Things
header-img: img/home-bg.jpg
email: phil@windley.org
description: "Things working together for you"
baseurl: ""
url: "http://societyofthings.org"
twitter_username: windley
github_username:  windley
facebook_username:  windley

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
